AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Summarize and transcribe clinical encounter mp3 files

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: API Gateway
      StageName: Dev
      Cors: "'*'"
      Auth:
          ApiKeyRequired: false
      
  
  TransriberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/transcriber
      Handler: transcriber.lambda_handler
      Runtime: python3.9
      Events:
        UploadMP3:
          Type: Api
          Properties:
            Path: /upload
            Method: post
            RestApiId:
              Ref: ApiGateway
  
  SummarizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/summarizer
      Handler: summarizer.lambda_handler
      Runtime: python3.9
  
  SummarizeTranscibeStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/transcibe_summarize.asl.json
      DefinitionSubstitutions:
        SummarizerFunctionArn: !GetAtt SummarizerFunction.Arn
        TransriberFunctionArn: !GetAtt TransriberFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref SummarizerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref TransriberFunction
  
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: StateMachineLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "lambda:InvokeFunction"
                Resource:
                  - !GetAtt SummarizerFunction.Arn
                  - !GetAtt TransriberFunction.Arn

Outputs:
  ApiGateway:
    Description: 'API Gateway endpoint URL for Dev stage for Hello World function'
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Dev/upload/'